#!/bin/bash
#SBATCH -n 2
#SBATCH -N 2
#SBATCH -t 0-12:00 #Request time
#SBATCH -p newnodes
#SBATCH -o output_%j.txt #redirect output to output_JOBID.txt
#SBATCH -e output_%j.txt #redirect errors to output_JOBID.txt

#filenames=("11" "13")
#filenames=("17" "19")
#filenames=("23" "29")
filenames=("31" "39")
# "5" "7" "11" "13" "17" "23")

for str in "${filenames[@]}"
do
  srun -N1 -n1 BN_sample_call_file "$str" &

done

wait

