#!/bin/bash
#SBATCH -n 8
#SBATCH -N 8
#SBATCH -t 0-12:00 #Request time
#SBATCH -p newnodes
#SBATCH -o output_%j.txt #redirect output to output_JOBID.txt
#SBATCH -e output_%j.txt #redirect errors to output_JOBID.txt

#filenames=("1" "2" "3" "4" "5" "6" "7" "8")
#filenames=("9" "10" "11" "12" "13" "14" "15" "16")
#filenames=("17" "18" "19" "20" "21" "22" "23" "24")
#filenames=("25" "26" "27" "28" "29" "30" "31" "32")
#filenames=("33" "34" "35" "36" "37" "38" "39" "40")
#filenames=("41" "42" "43" "44" "45" "46" "47" "48")
#filenames=("49" "50" "51" "52" "53" "54" "55" "56")
#filenames=("57" "58" "59" "60" "61" "62" "63" "64")
#filenames=("65" "66" "67" "68" "69" "70" "71" "72")
#filenames=("73" "74" "75" "76" "77" "78" "79" "80")
#filenames=("81" "82" "83" "84" "85" "86" "87" "88")
#filenames=("89" "90" "91" "92" "93" "94" "95" "96")
#filenames=("97" "98" "99" "100" "101" "102" "103" "104")
#filenames=("105" "106" "107" "108" "109" "110" "111" "112")
#filenames=("113" "114" "115" "116" "117" "118" "119" "120")
filenames=("121" "122" "123" "124" "125" "126" "127" "128")
pref="SA_QoI_bank"

for str in "${filenames[@]}"
do
  srun -N1 -n1 SA_QoI_call_file "$pref$str" &

done

wait

