import sys
import os
import scipy.stats
import math
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib import colormaps
import numpy as np
from scipy.interpolate import griddata
import csv
import dill

sys.path.append('../..')
#problem
from problems.rover_mif.rover_reliability_problem import *
#analysis
from obed.obed_huan import *
#from obed.obed_gbi import *
#from obed.pdf_estimation import *
#from inference.bn_modeling import *
#from inference.bn_evaluation import *
from uq.uncertainty_propagation import *
#from uq.sensitivity_analysis import *
#from uq.saltelli_gsa import *
#from uq.gsa_convergence import *
from opt.nsga import *

################################
#Useful definitions
################################

################################
#Analysis functions
################################

def vv_eval_problem(problem):
	print(problem)
	res = 400
	worst_case_theta = [1]*problem.dim_theta
	worse_case_downtime = problem.H(worst_case_theta)
	print(worse_case_downtime)
	
	#do a problem sample:
	tt = problem.prior_rvs(1)
	dd = [1000]*problem.dim_d
	Q = problem.H(tt)
	print(Q)
	y = problem.eta(tt, dd)
	print(y)
	
	"""
	def easy_eta(t,d):
		return problem.eta([t], [d], err=False)[0]
	vectorized_eta = np.vectorize(easy_eta)
	
	ds = np.linspace(problem.d_dists[0][1][0],problem.d_dists[0][1][1],res)
	ts = np.linspace(0,1,res) #the domain of the gamma fn
	
	D, T = np.meshgrid(ds, ts)
	Y = vectorized_eta(T, D)
	img = plt.pcolormesh(D, T, Y, cmap="inferno", shading="auto")
	plt.colorbar(img, label="y = eta(theta,d)")
	plt.ylabel('theta')
	plt.xlabel('d')
	plt.show()
	"""
	
def vv_UA(problem, n):
	theta_prior_samples = problem.prior_rvs(n)
	print(theta_prior_samples)
	uncertainty_prop_plots(theta_prior_samples, xlabs=problem.theta_names, saveFig='', doLog=True)
	
def vv_UP(problem, n):
	theta_prior_samples = problem.prior_rvs(n)
	Qs = [problem.H(theta) for theta in theta_prior_samples]
	uncertainty_prop_plot(Qs, xlab="total downtime [hr]", saveFig='', bins=100, doLog=True)
	print("average downtime:",np.mean(Qs))
	print("there is a 95% probability that the downtime is less than",np.quantile(Qs,0.95))

#Uncertainty analysis of the experiment models
def vv_UP_exp(problem, dd, theta_nominal, n=10**4, savefig=False):
	print("Likelihood distribution for","(theta="+str(theta_nominal[0]),"d="+str(dd[0])+" hr)","case:",flush=True)
	#tt = problem.prior_rvs(1); print(tt)
	tt = theta_nominal
	ysample_nominal = [problem.eta(tt, dd) for _ in range(n)]
	uncertainty_prop_plots(ysample_nominal, xlabs=problem.y_names, saveFig='UP_exp_nominal' if savefig else '')
	
	#Also plot the y's generated by the joint distribution p(y|theta,d)p(theta)
	print("Experiments simulated from the joint distribution","for d="+str(dd[0])+" hr):",flush=True)
	uq_thetas = problem.prior_rvs(n)
	uq_ys = [problem.eta(theta, dd) for theta in uq_thetas]
	uncertainty_prop_plots(uq_ys, c='orchid', xlabs=problem.y_names, saveFig='UP_joint_y0' if savefig else '')

def vv_gbi_test(problem, d, N, y=[], ncomp=0):		
	print("Training...")
	theta_train = problem.prior_rvs(N)
	qoi_train = [problem.H(theta) for theta in theta_train]
	y_train = [problem.eta(theta, d) for theta in theta_train]
	
	gmm = gbi_train_model(theta_train, qoi_train, y_train, verbose=2, ncomp=ncomp)
	
	if y==[]:
		print("Determining random measurement Yd...")
		truth_theta = problem.prior_rvs(1)
		Yd = problem.eta(truth_theta, d)
	else:
		Yd = y
	
	print("Conditioning...")
	a,b,c = gbi_condition_model(gmm, Yd, verbose=2)
	
	if y==[]:
		plot_predictive_posterior(a, b, c, 0, 500, drawplot=False, plotmean=True)
		plt.axvline(problem.H(truth_theta), c='blue')
		plt.show()
	else:
		plot_predictive_posterior(a, b, c, 0, 500, drawplot=True)
		
def vv_OPT(problem, design_pts, epsilon, util_err, do_hrs, do_min, threads, popSize, nMC, displayFreq=10):
	#Load the GMM and presampled y from file
	costs, utilities, designs = nsga2_obed_builtin(	
					n_threads=threads, 
					prob=problem, 
					hours=do_hrs, 
					minutes=do_min, 
					popSize=popSize, 
					nSkip=2, 
					tolDelta=epsilon,#utility_conf95/1.96, 
					nPeriod=5, 
					nMonteCarlo=nMC, 
					displayFreq=displayFreq
				)
	plot_nsga2(costs, utilities, design_pts, util_err=util_err, showPlot=True, savePlot=False, logPlotXY=[False,False])

	

if __name__ == '__main__':  
	import argparse
	parser = argparse.ArgumentParser()
	parser.add_argument('--run', metavar='string', required=True, help='Function to run for this vvopt analysis')
	parser.add_argument('-n', type=int, default=0, help='Number of iterations to give to the function')
	parser.add_argument('-v', type=float, default=0, help='Function value input')
	args = parser.parse_args()

	problem = make_rover_reliability_problem()

	###Uncertainty Quantification
	if args.run == "eval_problem":
		vv_eval_problem(problem)
		
	elif args.run == "UA":
		vv_UA(problem, n=args.n)
		
	elif args.run == "UP":
		vv_UP(problem, n=args.n)
		
	elif args.run == "UP_exp":
		vv_UP_exp(problem, [2300], [lambda_avg], n=args.n, savefig=False)
		
	elif args.run == "SA":
		problem.sensitivity_analysis(doPlot=True)
		
	elif args.run == "OBED_test":
		d_test = [int(args.v)]*problem.dim_d
		U, us = problem.utility(d=d_test, n_MC=args.n)
		print(U)
		
	elif args.run == "OBED_convergence":
		d_example = [300]*problem.dim_d
		n_max = 1000000
		
		#Calculate utility for a number of n_mc
		_, u_list = problem.utility(d=d_example, n_MC=n_max)
		mc_plot_trace_bootstrap(u_list, 60, doLog=False, doEvery=10000)

	elif args.run == "OPT":
		vv_OPT(
			problem, 
			design_pts=[],
			epsilon=0.3,
			util_err=0.3,
			do_hrs = 0,
			do_min = 0,
			threads = 1 if args.n==0 else args.n,
			popSize=40,# if args.n==0 else args.n,
			nMC=100000,
			displayFreq=10
		)
	
	else:
		print("I dont recognize the command",args.run)
