import sys
import os
import scipy.stats
import math
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib import colormaps
import numpy as np
from scipy.interpolate import griddata
import csv
import dill

sys.path.append('../..')
#problem
from problems.rover_mif.single_mif_problem import *
#analysis
from obed.obed_huan import *
#from obed.obed_gbi import *
#from obed.pdf_estimation import *
#from inference.bn_modeling import *
#from inference.bn_evaluation import *
from uq.uncertainty_propagation import *
#from uq.sensitivity_analysis import *
#from uq.saltelli_gsa import *
#from uq.gsa_convergence import *
#from opt.nsga import *

################################
#Useful definitions
################################

################################
#Analysis functions
################################

def vv_eval_problem(problem):
	print(problem)
	res = 400
	
	def easy_eta(t,d):
		return problem.eta([t], [d], err=False)[0]
	vectorized_eta = np.vectorize(easy_eta)
	
	ds = np.linspace(problem.d_dists[0][1][0],problem.d_dists[0][1][1],res)
	ts = np.linspace(0,1,res) #the domain of the gamma fn
	
	D, T = np.meshgrid(ds, ts)
	Y = vectorized_eta(T, D)
	img = plt.pcolormesh(D, T, Y, cmap="inferno", shading="auto")
	plt.colorbar(img, label="y = eta(theta,d)")
	plt.ylabel('theta')
	plt.xlabel('d')
	plt.show()
	
def vv_UA(problem, n=10**5):
	theta_prior_samples = problem.prior_rvs(n)
	print(theta_prior_samples)
	uncertainty_prop_plots(theta_prior_samples, xlabs=problem.theta_names, saveFig='')

#Uncertainty analysis of the experiment models
def vv_UP_exp(problem, dd, theta_nominal, n=10**4, savefig=False):
	print("Likelihood distribution for","(theta="+str(theta_nominal[0]),"d="+str(dd[0])+" hr)","case:",flush=True)
	#tt = problem.prior_rvs(1); print(tt)
	tt = theta_nominal
	ysample_nominal = [problem.eta(tt, dd) for _ in range(n)]
	uncertainty_prop_plots(ysample_nominal, xlabs=problem.y_names, saveFig='UP_exp_nominal' if savefig else '')
	
	#Also plot the y's generated by the joint distribution p(y|theta,d)p(theta)
	print("Experiments simulated from the joint distribution","for d="+str(dd[0])+" hr):",flush=True)
	uq_thetas = problem.prior_rvs(n)
	uq_ys = [problem.eta(theta, dd) for theta in uq_thetas]
	uncertainty_prop_plots(uq_ys, c='orchid', xlabs=problem.y_names, saveFig='UP_joint_y0' if savefig else '')

def vv_gbi_test(problem, d, N, y=[], ncomp=0):		
	print("Training...")
	theta_train = problem.prior_rvs(N)
	qoi_train = [problem.H(theta) for theta in theta_train]
	y_train = [problem.eta(theta, d) for theta in theta_train]
	
	gmm = gbi_train_model(theta_train, qoi_train, y_train, verbose=2, ncomp=ncomp)
	
	if y==[]:
		print("Determining random measurement Yd...")
		truth_theta = problem.prior_rvs(1)
		Yd = problem.eta(truth_theta, d)
	else:
		Yd = y
	
	print("Conditioning...")
	a,b,c = gbi_condition_model(gmm, Yd, verbose=2)
	
	if y==[]:
		plot_predictive_posterior(a, b, c, 0, 500, drawplot=False, plotmean=True)
		plt.axvline(problem.H(truth_theta), c='blue')
		plt.show()
	else:
		plot_predictive_posterior(a, b, c, 0, 500, drawplot=True)
	

if __name__ == '__main__':  
	import argparse
	parser = argparse.ArgumentParser()
	parser.add_argument('--run', metavar='string', required=True, help='Function to run for this vvopt analysis')
	parser.add_argument('-n', type=int, default=0, help='Number of iterations to give to the function')
	parser.add_argument('-v', type=float, default=0, help='Function value input')
	parser.add_argument('--filename', metavar='string', default="SA_QoI", help='Base name to five to SA_QoI_sample')
	args = parser.parse_args()

	problem = make_single_mif_problem()

	###Uncertainty Quantification
	if args.run == "eval_problem":
		vv_eval_problem(problem)
		
	elif args.run == "UA":
		vv_UA(problem, n=args.n)
		
	elif args.run == "UP_exp":
		lambda_avg = problem.prior_mean_dict['motor drive electronics fail rate [per hr]']
		print("Average prior failure rate:",lambda_avg)
		vv_UP_exp(problem, [2300], [lambda_avg], n=args.n, savefig=False)
		
	elif args.run == "OBED_test":
		print(problem.utility(d=args.v, n_MC=args.n))

	elif args.run == "OBED_full":
		#Calculate U for range of different designs
		res=int(args.v)
		ds = np.linspace(problem.d_dists[0][1][0],problem.d_dists[0][1][1],res)
		Us = [0]*len(ds)
		for j,d in enumerate(ds):
			U = problem.utility(d, n_MC=args.n)
			Us[j] = U
			print(d, U)
		
		plt.plot(ds,Us)
		plt.xlabel("d [hours spent on rover test]")
		plt.ylabel("U(d) [utility of design]")
		plt.title("")
		plt.show()
	
	else:
		print("I dont recognize the command",args.run)
